#112 - bugfix to work as intended.
johrstrom/jmeter-prometheus-plugin pull request #113
Opened 2023-02-08 09:06 UTC by keydam

It now works as intended, can you check ?

2023-02-10 03:27 UTC, swatson31 requested changes
I'm not an official maintainer of this repo, but I found it very useful at work. I care about the future of this code.  I have a few concerns about this change which are called out at the specific line numbers...

2023-02-10 03:27 UTC, swatson31 commented on CHANGELOG.md
> +* #112 - bugfix to work as intended.
I suggest describing what was fixed. This comment isn't very helpful without digging into the related code changes.

2023-02-10 03:27 UTC, swatson31 commented on src/main/java/com/github/johrstrom/listener/PrometheusServer.java
> +    	server.stop(0);
I haven't looked deeper, but I wonder if the problem should be fixed inside of the stop() method. It looks like non-zero stop() is broken by the way you fixed this. I think you should at least leave a comment explaining why fixing the server.stop() method is not preferred.

2023-02-10 03:35 UTC, swatson31 commented on src/main/java/com/github/johrstrom/listener/PrometheusServer.java
> +    	server.stop(0);
I found the issue you created and read [the doc you linked](https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpServer.html#stop-int-). I would support this change with at least a more descriptive change in the CHANGELOG.  👍

2023-02-10 14:47 UTC, johrstrom commented
Hi, thanks for the pull request. I'll try to look into this weekend. I lost the gpg key I used to sign these jars so I've got to figure some way to release.

That said - on the surface it looks OK, but I'll have to check the docs on `stop` a little.

2023-02-21 15:00 UTC, keydam commented
Any news ?
I can indeed be more specific in the changelog if necessary

2023-02-21 16:21 UTC, johrstrom commented
Hi, sorry for the delay. No, there's nothing more on your side I require I just need to find the time is all. I can't work on this at work, so I need to free up some personal time to get it all sorted & released.

2023-02-22 21:53 UTC, johrstrom commented
I was going to pull this in, but it doesn't look like the commit you made is actually tied to your github user.  Meaning, you're github account https://github.com/keydam is not going to be credited with the commit (an unknown user is).

You can fix the commit if you like. I'd suggest you do just so you get the proper credit.

Aside from that - I'm working on automation to make releases. As I've said, I've lost the gpg key I used to sign these to upload to maven, so 0.6.1 (the next version) may just be attached to this repo and not on maven.  That siad, I'll still work to actually upload them to maven central as well.

2023-02-22 22:34 UTC, closed without merging